name: AzisabaAchievements
api-version: 1.13
version: @version@
main: net.azisaba.azisabaachievements.spigot.plugin.SpigotPlugin
commands:
  azisabaachievements:
    permission: azisabaachievements.command.azisabaachievements
    aliases: ["achievements"]
