name: AzisabaAchievements
api-version: 1.13
version: @version@
main: net.azisaba.azisabaachievements.spigot.SpigotPlugin
commands:
  azisabaachievements:
    permission: azisabaachievements.command.azisabaachievements
